config/routes.rb
Iat222::Application.routes.draw do
  mount Mercury::Engine => '/'

  devise_for :users, controllers: { registrations: "registrations" }, :path_names => { :sign_in => 'signin', :sign_out => 'signout', :sign_up => 'signup' }

  root to: 'home#index'

  authenticated :user do
  	resources :pages do
  		member { post :mercury_update }
  	end
  	get '/admin' => 'home#admin'
  end

  get '/:name' => 'pages#show'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
    # elsif user.has_role? :moderator
      can :edit, :all
    else
      can :read, :all
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :name, :title

  before_save :downcase_and_combine_name
  before_save :titleize_title

  def downcase_and_combine_name
  	self.name = self.name.downcase.gsub(" ", "_")
  end

  def titleize_title
  	self.title = self.title.titleize
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def permalink name
	"/#{name}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def admin
  	@users = User.all
  	authorize! :manage, :admin, message: "Access denied."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    if params[:name]
      @page = Page.find_by_name(params[:name])
      raise ActiveRecord::RecordNotFound, "Page not found" if @page.nil?
    else
      @page = Page.find(params[:id])
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to permalink(@page.name), notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to permalink(@page.name), notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def mercury_update
    page = Page.find(params[:id])
    page.name = params[:content][:page_name][:value]
    page.content = params[:content][:page_content][:value]
    page.save!
    render text: ""
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def update
		@user = User.find(current_user.id)
		email_changed = @user.email != params[:user][:email]
		password_changed = !params[:user][:password].empty?
		successfully_updated = if email_changed or password_changed
			@user.update_with_password(params[:user])
		else
			params[:user].delete("current_password")
			@user.update_without_password(params[:user])
		end

		if successfully_updated
			sign_in @user, bypass: true
			redirect_to root_url, notice: "Your profile is successfully updated."
		else
			render 'edit'
		end
	end

	private

		def build_resource(*args)
			super
			accepted_emails = %w[
				historywhiz4k@gmail.com
				amandamutsaerts@hotmail.com
				hobby347@gmail.com
				soeuna@sfu.ca
				eshinep@sfu.ca
			]
			if accepted_emails.include? resource.email
				resource.add_role(:user)
			else
				resource.add_role(:unauthorized)
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def all_pages
		Page.all
	end

	def permalink name
		"/#{name}"
	end

	def markdown(text)
		options = [:autolink => true,
				:space_after_headers => true,
				:filter_html => true,
				:no_intra_emphasis => true,
				safe_links_only: true]
		md = Redcarpet::Markdown.new(Redcarpet::Render::HTML, *options)

		md.render(text).html_safe
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/admin.html.erb
<h1>admin home page</h1>

<strong>Currect Users</strong>
<ul>
<% @users.each do |user| %>
	<li><%= user.email %></li>
<% end %>
</ul>

app/views/home/index.html.erb
<div class="jumbotron">
	<div class="row-fluid marketing">
		<h1 style="font-size: 4em">Artsy butterfly project</h1>
		<h4>We are Team TWOTWOTWO. This is our project website.</h4>
		<div id="carousel" class="carousel slide">
		  <!-- Carousel items -->
		  <div class="carousel-inner">
		    <div class="active item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1779.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1780.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1781.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1782.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1783.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1791.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1794.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1812.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1814.JPG" alt=""></div>
		    <div class="item"><img src="https://dl.dropbox.com/u/1775921/ButterflyPhotos/IMG_1818.JPG" alt=""></div>
		  </div>
		  <!-- Carousel nav -->
		  <a class="carousel-control left" href="#carousel" data-slide="prev">&lsaquo;</a>
		  <a class="carousel-control right" href="#carousel" data-slide="next">&rsaquo;</a>
		</div>
	</div>

<hr>
	<p class="lead">For more information, please check out our <%= link_to "about page", permalink("about") %> or click the button below for more details on the project.</p>
	<%= link_to "Check out the project", permalink("project"), class: 'btn btn-large btn-success' %>
	<!-- <div class="span6">
		<h4>Interactions</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div>

	<div class="span6">
		<h4>Physical installations</h4>
		<p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		<h4>Subheading</h4>
		<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		<h4>Subheading</h4>
		<p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
	</div> -->
</div>

app/views/layouts/_msg.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<div class="alert alert-<% if name == :notice %>success<% elsif name == :alert %>error<% else %><%= name %><% end %> fade in"> <!-- error, success, info, block(for longer msg) -->
			<button class="close" data-dismiss="alert">&#215;</button>
			<%= content_tag :div, msg, class: "flash_#{name}" %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_nav.html.erb
<ul class="nav nav-pills pull-right">
	<li <%= "class=active" if current_page?(root_path) %>><%= link_to "Home", root_path %></li>
	
	<% all_pages.each do |page| %>
		<li <%= "class=active" if current_page?(permalink(page.name)) %>><%= link_to page.title, permalink(page.name) %></li>
	<% end %>
	
	<% if user_signed_in? %>
		<% if current_user.has_role?(:admin) %>
			<li <%= "class=active" if current_page?(admin_path) %>><%= link_to "Admin", admin_path %></li>
		<% end %>
		<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title)+" | IAT 222 Project" : "IAT 222 Project" %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= favicon_link_tag %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <%= yield(:head) %>
</head>
<body>
	<div class="container-narrow">
		<%= render 'layouts/msg' %>
		<% if user_signed_in? && current_user.has_role?(:unauthorized) %>
			<%= content_tag :div, "You can't edit the pages because your account is unauthorized.", class: "alert alert-error fade in" %>
		<% end %>
		<div class="masthead">
			<%= render 'layouts/nav' %>
			<h3 class="muted"><%= link_to "Artsy Butterfly", root_path, class: "muted" %></h3>
		</div>
		
		<hr>
			
		<%= yield %>
		
		<hr>

		<div class="footer">
			<p>&copy;2012 - Team TWOTWOTWO 
			<% if user_signed_in? %>
				<span style="float:right">Logged in as <%= link_to current_user.email, edit_user_registration_path %></span>
			<% else %>
				<span style="float:right; margin-left: 16px"><%= link_to "Sign in", new_user_session_path %></span>
				<span style="float:right"><%= link_to "Sign up", new_user_registration_path %></span>
			</p>
			<% end %>
		</div>
	</div>    
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :title, label: "Page title", placeholder: "title of the page" %>
  </div>
  <div class="field">
    <%= f.input :name, label: "Page name", hint: "will be used for the url", placeholder: "http://example.com/page_name" %>
  </div>

  <br>

  <div class="field">
    <%= f.input :content, placeholder: "content of the page" %>
  </div>
  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<div class="row">

<div class="span4">
	<%= render 'form' %>
	<%= link_to 'Delete', page_path(@page), method: :delete, confirm: "Are you sure?" %> |
	<%= link_to 'Back', :back %>
</div>

<div class="span5">
	<div class="hero-unit" style="padding: 15px">
		<h2>## Heading 2</h2>
		<h3>### Heading 3</h3>
		<h4>#### Heading 4</h4>
		<h5>##### Heading 5</h5>

		_<i>Italic</i>_
		<br>
		__<b>Bold</b>__
		<br>
		<br>

			* Bullet point
			<br>
			* Bullet point

		<br>
		<br>

			1. Ordered List
			<br>
			2. Ordered List

		<br>
		<br>

		![image](http://image-url)
		<br>
		<br>
		double space on the end of line is a line break
		<br>
		double enter is new paragraph

		<br>
		<br>
		___ Horizontal rule (needs to be in a new paragraph)

	</div>
</div>

</div>

app/views/pages/index.html.erb
<h1>All Pages</h1>

<% @pages.each do |page| %>
  <ul>
    <li><%= link_to page.title, permalink(page.name) %></li>
    <ul>
      <li><%= link_to 'Edit', edit_page_path(page) %></li>
      <li><%= link_to 'Delete', page, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </ul>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<% title @page.title %>

<h1><span id="page_name" class="mercury-region" data-mercury="full"><%= @page.name %></span></h1>

<%# simple_format @page.content, {}, sanitize: false %>

<div id="page_content" class="mercury-region" data-mercury="full">
	<%= markdown(@page.content) %>
</div>

<% if user_signed_in? && !current_user.has_role?(:unauthorized) %>
	<p>
		<%# link_to 'Edit', edit_page_path(@page) %>
		<%= link_to 'Edit', "/editor" + page_path(@page), id: "edit_link", data: {save_url: mercury_update_page_path(@page)} %> <span class="pipe">|</span>
		<%= link_to 'Back', permalink(@page.name) %>
	</p>

	<script>
		$(window).on('mercury:ready', function() {
		  Mercury.saveUrl = <%= raw('"' + mercury_update_page_path(@page) + '"') %>;
		  $('.pipe').hide();
		});
	</script>
<% end %>